### ISSUE TITLE
It is not micro

### ISSUE THREAD

**Issue by petrkr** [HWHardsoft/micropyMeterBus#2]
On ESP32 without external PSRAM it even does not imports. It will ate whole free memory

```
Traceback (most recent call last):
  File "main.py", line 2, in <module>
  File "/lib/meterbus/__init__.py", line 21, in <module>
  File "/lib/meterbus/telegram_control.py", line 1, in <module>
  File "/lib/meterbus/telegram_body.py", line 3, in <module>
  File "/lib/meterbus/telegram_variable_data_record.py", line 1, in <module>
MemoryError: memory allocation failed, allocating 136 bytes
```

Simple example just

```
from machine import UART, Pin
import meterbus.serial
import time
import meterbus

ser = UART(1, 2400, bits=8, parity=0, stop=1,  tx=4, rx=36)

```

would be nice to optimize it for low memory environments too to make it micro

also tried even simple import

```
>>> gc.mem_free()
101488
>>> gc.collect()
>>> gc.mem_free()
103280
>>> import meterbus
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/lib/meterbus/__init__.py", line 21, in <module>
  File "/lib/meterbus/telegram_control.py", line 1, in <module>
  File "/lib/meterbus/telegram_body.py", line 3, in <module>
  File "/lib/meterbus/telegram_variable_data_record.py", line 1, in <module>
MemoryError: memory allocation failed, allocating 640 bytes
```

**Comment by petrkr** [comment]
In case if I will precompile mpy_decimal to mpy, I am able to import, but not too much memory left, that will not be useable for SSL connections, where is atleast 30-40kB needed

```
>>> import meterbus
>>> gc.mem_free()
22496
>>> gc.collect()
>>> gc.mem_free()
26288
```

**Comment by petrkr** [comment]
after precompile to mpy it just raise 1kB

```
>>> gc.collect()
>>> import meterbus
>>> gc.mem_free()
25728
>>> gc.collect()
>>> gc.mem_free()
27536
```

I barely go through code, there are lot of unsused / reserved index, which can be reduced to just unsupported in some logic in code, do not need load to mem 100 lines of "reserved" dictionaries

**Comment by JonnoFTW** [comment]
This code is directly lifted from this repo: https://github.com/ganehag/pyMeterBus
